### ISSUE TITLE
Adjust sizing with substitute images

### ISSUE THREAD

**Issue by tu-annguyen** [curtinlibrary/virtual-bookshelf#1]
Hello, I am trying to adjust the size of the bookshelf with substitute images, but I am having trouble with the spacing between images.

I doubled the size of the substitute images in `./substitute.css`:
```css
.shelf-image-container {
	width: 290px;
	height: 400px;
	...
}
.shelf-image-substitute {
	width: 290px;
	height: 400px;
	...
}
```

I was able to adjust the spacing of the images while initializing the `VirtualBookshelf`:
```javascript
const bookshelf = new VirtualBookshelf.Bookshelf('#bookshelf', {
	spacing: 1.1,
	itemAspect: 0.725,
	...
}
```
While the spacing between substitute images is fine:

![image](https://github.com/user-attachments/assets/0fdcd4e0-af01-4f3c-827f-c1cb1b5eb542)

The spacing to the right of non-substitute images (highlighted in red) are significantly larger than the spacing to the right of substitute images (highlighted in blue):

![image](https://github.com/user-attachments/assets/7806204b-6512-49bd-a5aa-d190e5467269)

Is there a way to make the spacing more consistent?

**Comment by tu-annguyen** [comment]
I've found a workaround, but it's not ideal. I reduced the width of the `shelf-img-substitute`:

```css
.shelf-image-substitute {
	width: 229px;
	height: 400px;
}
```

The spacing is more consistent now, albeit quite large:
![image](https://github.com/user-attachments/assets/876b29d0-50a6-4852-8dd3-1e77b2e19597)
